services:
  postgres:
    image: postgres
    env_file:
      - D:\Carsties\src\env\postgres_env.env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: